server:
  port: 3333

database:
  type: 'postgres'
  port: 5432
  database: 'chartsdb'
  host: '0.0.0.0'
  username: 'postgres'
  password: 'root'
  synchronize: true

jwt:
  secret: 'super@s3cr3t'
  expiresIn: '365d'
